inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Style/Encoding:
  Enabled: true

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/LineLength:
  Max: 120
