default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: imgosaurus_development

test:
  <<: *default
  database: imgosaurus_test

production:
  <<: *default
  database: imgosaurus_production
  username: imgosaurus
  password: <%= ENV['IMGOSAURUS_DATABASE_PASSWORD'] %>
